name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make package
      run: make package
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: packages
