name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
    - name: make package
      run: make package
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ runner.arch }}
        path: packages
  build_arm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04
            headers: linux-headers-generic
          - arch: armv6
            distro: buster
            headers: raspberrypi-kernel-headers
          - arch: armv7
            distro: buster
            headers: linux-headers-armmp
    steps:
    - uses: actions/checkout@v1
    - uses: uraimo/run-on-arch-action@master
      name: Run commands
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        githubToken: ${{ github.token }}
        setup: |
          mkdir -p "${PWD}/packages"
        dockerRunArgs: |
          --volume "${PWD}/packages:/packages"
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DOS_VERSION=generic -DBUILD_MODULE=OFF .
          make
          make package
        install: |
          apt-get update -q -y
          apt-get install -y cmake build-essential ${{ matrix.headers }}
          if [ ${{ matrix.distro }} = "buster" ]; then
            # cmake 3.16 has problems
            apt-get remove -y cmake-data
            apt-get install -y cmake-data=3.13.4-1 cmake=3.13.4-1
          fi
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ matrix.arch }}-${{ matrix.distro }}
        path: packages

  merge_artifacts:
    runs-on: ubuntu-latest
    needs: [build, build_arm]
    steps:
    - name: Merge Artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        delete-merged: true
        name: packages
        pattern: packages-*
